#! /usr/bin/env python
import numpy as np
import pyaudio
import sys

CHUNK = 1024
FORMAT = pyaudio.paInt16
CHANNELS = 1
RATE = 44100


def play(data):
    p = pyaudio.PyAudio()

    stream = p.open(
        format=FORMAT,
        channels=CHANNELS,
        rate=RATE,
        output=True)

    data = np.iinfo(np.int16).max * data
    data = data
    frames = [
        f.astype(np.int16).tostring()
        for f in data.reshape(-1, CHUNK)]

    for f in frames:
        stream.write(f)

    stream.stop_stream()
    stream.close()

    p.terminate()


if __name__ == "__main__":
    if len(sys.argv) > 2:
        duration = float(sys.argv[2])
    else:
        duration = 0.3

    freq = int(sys.argv[1])

    nchunks = (RATE*duration + CHUNK-1)//CHUNK
    nsamples = nchunks*CHUNK

    t = np.linspace(0, duration, nsamples)
    data = np.sin(freq*2*np.pi*t)

    ramp = np.linspace(0, 1, nsamples)
    data = data * (1-ramp)**2

    play(data)
