#! /bin/sh

set -e

if test "$1" = ""; then
  echo "usage: $0 FILEROOT"
  exit 1
fi

ROOT="${1%%.mkv}"
if test "$ROOT" = "$1"; then
  echo "file $1 does not end in mkv"
  exit 1
fi
SRC="$ROOT.mkv"
if ! test -f "$SRC" ; then
  echo "file $SRC does not exist"
  exit 1
fi

mkdir -p encoded

TGT_WEBM="encoded/$ROOT.webm"
if test -f "$TGT_WEBM" ; then
  echo "file $TGT_WEBM already exists"
  exit 1
fi
TGT_MP4="encoded/$ROOT.mp4"
if test -f "$TGT_MP4" ; then
  echo "file $TGT_MP4 already exists"
  exit 1
fi
TGT_JPEG="encoded/$ROOT.jpeg"
if test -f "$TGT_JPEG" ; then
  echo "file $TGT_JPEG already exists"
  exit 1
fi

# {{{ webm encode

echo "--------------------------------------------"
echo "webm encode"
echo "--------------------------------------------"

gst-launch-1.0 \
    filesrc location="$SRC" ! decodebin name=demux \
    webmmux name=wmux ! filesink location="$TGT_WEBM" \
    \
    demux. \
    ! queue \
    ! videoconvert \
    ! vp8enc threads=4 \
    ! wmux. \
    \
    demux. \
    ! queue \
    ! progressreport \
    ! audioconvert \
    ! audioresample \
    ! vorbisenc \
    ! wmux. \

# }}}

# {{{ mp4 encode

echo "--------------------------------------------"
echo "mp4 encode"
echo "--------------------------------------------"

gst-launch-1.0 \
    filesrc location="$SRC" ! decodebin name=demux \
    mp4mux name=wmux ! filesink location="$TGT_MP4" \
    \
    demux. \
    ! queue \
    ! videoconvert \
    ! x264enc threads=4 \
    ! "video/x-h264,profile=(string)baseline" \
    ! wmux. \
    \
    demux. \
    ! progressreport \
    ! audioconvert \
    ! audioresample \
    ! voaacenc \
    ! wmux. \

# }}}

avconv -i "$TGT_MP4" -ss "3" -vframes 1 -vcodec mjpeg -f image2 "$TGT_JPEG"

# vim: foldmethod=marker
